apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cachier-controller-admin
subjects:
  - kind: ServiceAccount
    name: cachier-controller
    namespace: cachier-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
